config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get "home/about" => "home#about"
  devise_for :users
  resources :books
  resources :users, only: [:show, :index, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

belongs_to :user

validates :title, presence: true
validates :body, presence: true, length: {maximum:200}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image

  validates :name, presence: true, length: {minimum: 2, maximum: 20}
  validates :introduction, length: {maximum:50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  protected
  def configure_permitted_parameters
    added_attrs = [ :email, :name, :password, :password_confirmation ]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: 'You have created book successfully.'
    else
      @books = Book.all.reverse_order
      @user = User.find_by(id: current_user.id)
      @newbook = @book
      render 'index'
    end
  end

  def index
    @user = User.find_by(id: current_user.id)
    @newbook = Book.new
    @books = Book.all.reverse_order
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @user = User.find_by(id: @book.user_id)
    @newbook = Book.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: 'You have updated book successfully.'
    else
      render 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book_user_id == current_user.id
      @book.destroy
    end
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!
  
  def index
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @newbook = Book.new
    @books = @user.books.reverse_order
  end

  def index
    @users = User.all
    @user = User.find_by(id: current_user.id)
    @newbook = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
    else
      render 'edit'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1>Editing Book</h1>

      <% if @book.errors.any? %>
        <div id="error_explanation" class="alert alert-danger">
          <h3><%= @book.errors.full_messages.count %> errors prohibited this obj from being saved:</h3>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%= form_for(@book) do |f| %>
        <div class="field row">
          <label for="book_title">Title</label><br>
          <%= f.text_field :title, class: "col-xs-12" %>
        </div>
        <div class="field row">
          <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, class: "col-xs-12" %>
        </div>
        <div class="actions row">
          <%= f.submit "Update Book", class: "btn btn-primary col-xs-12" %>
        </div>
      <% end %>

      <%= link_to "Show", book_path(@book) %> | <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
  <%= notice %>

  <% if @book.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h3><%= @book.errors.full_messages.count %> errors prohibited this obj from being saved:</h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="row">
    <%= render 'users/list', user: @user, book: @book %>
    
    <div class="col-xs-9">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user_id), target: "_self" do %>
                  <%= attachment_image_tag book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size:"40x40" %>
                <% end %>
              </td>
              <td><%= link_to book_path(book.id) do %><%= book.title %><% end %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <%= notice %>
  <div class="row">
    <%= render 'users/list', user: @user, book: @book_new %>
    
    <div class="col-xs-9">
      <h2>Book detail</h2>
      <table class="table table-hover table-inverse">
        <tbody>
            <tr>
              <td>
                <%= link_to user_path(@book.user.id), target: "_self" do %>
                  <%= attachment_image_tag @book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size:"40x40" %>
                  <br>
                  <%= @book.user.name %>
                <% end %>
              </td>
              <td><%= link_to book_path(@book.id) do %><%= @book.title %><% end %></td>
              <td><%= @book.body %></td>
              <% if @book.user.id == current_user.id %>
                <td><%= link_to "Edit", edit_book_path(@book.id), class: "btn-sm btn-success"%></td>
                <td><%= link_to "Destroy", book_path(@book.id), method: :delete, class: "btn-sm btn-danger", data: { confirm: "本当に消しますか？" } %></td>
              <% end %>
            </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/home/about.html.erb
<div class="container">
  <h1>
    Welcome to <span class="glyphicon glyphicon-book"></span>
    <strong>Bookers</strong>!
  </h1>
</div>

app/views/home/index.html.erb
<div class="container">
  <%= notice %>
  <div class="top-message col-md-offset-3 col-md-6">

    <h1>welcome to 
    <span class="glyphicon glyphicon-book"><strong>Bookers</strong> !!</span>
    </h1>
    <p>
    In <span class="glyphicon glyphicon-book"></span>
    <strong>Bookers</strong>,
    </p>
    <p>you can share and exchange your opinioins , inpressions , and emotions</p>
    <p>about various books!</p>
    <div class="btn-wrapper">
      <div class="row">
        <p>
          <%= link_to "Log in", user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1 sign_in" %>
        </p>
        <p>
          <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1 sign_up" %>
        </p>
      </div>
    </div>
  </div>

  <div id="container">
  <div id="theTarget">
    <div class="image1"></div>
    <div class="image2"></div>
    <div class="image3"></div>
    <div class="image4"></div>
    <div class="image5"></div>
  </div>
</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <nav class="nav navbar-nav navbar-left">
        <span>Bookers</span>
      </nav>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to " Home", user_path(current_user.id), class: "glyphicon glyphicon-home home" %></li>
            <li><%= link_to " Users", users_path, class: "glyphicon glyphicon-user users" %></li>
            <li><%= link_to " Books", books_path, class: "glyphicon glyphicon-book books" %></li>
            <li><%= link_to " logout", destroy_user_session_path, class: "glyphicon glyphicon-log-out logout", method: :delete %></li>            
          <% else %>
            <li><%= link_to " Home", root_path, class: "glyphicon glyphicon-home home" %></li>
            <li><%= link_to " About", home_about_path, class: "glyphicon glyphicon-link about" %></li>
            <li><%= link_to " sign up", new_user_registration_path, class: "glyphicon glyphicon-edit sign_up" %></li>
            <li><%= link_to " login", user_session_path, class: "glyphicon glyphicon-log-in sign_in" %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </header>

  <body>
    <%= yield %>
  </body>

  <footer>
    <div class="container">
      <div class="col-xs-3 col-xs-offset-9">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </footer>

</html>

app/views/users/_list.html.erb
    <div class="col-xs-3">
      <h2>User info</h2>
      <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
      <table class="table">
        <tbody>
          <tr></tr>
          <tr>
            <th>name</th>
            <th><%= user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= user.introduction %></th>
          </tr>
        </tbody>
      </table>
      <div class="row">
        <%= link_to "", edit_user_path(user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
      </div>

      <h2>New book</h2>
      <%= form_for(@newbook, url: books_path) do |f| %>
        <div class="field row">
          <label for="book_title">Title</label> <br>
          <%= f.text_field :title, class: "col-xs-12" %>
        </div>
        <div class="field row">
          <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, class: "col-xs-12" %>
        </div>
        <div class="actions row">
            <%= f.submit "Create Book", class: "btn btn-primary col-xs-12" %>
        </div>
      <% end %>
    </div>

app/views/users/edit.html.erb
<div class="container">
  <h2>User info</h2>

  <% if @user.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h3><%= @user.errors.full_messages.count %> errors prohibited this obj from being saved:</h3>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_for(@user) do |f| %>
    <div class="field">
      <label for="user_name">Name</label>
      <%= f.text_field :name, class: "name" %>
    </div>
    <div class="field">
      <label for="user_image">Image</label>
      <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user_image" %>
    </div>
    <div class="field">
      <label for="user_introduction">Introduction</label>
      <%= f.text_area :introduction, class: "introduction" %>
    </div>
    <div class="actions">
      <%= f.submit "Update User" %>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container">
  <%= notice %>
  <div class="row">
    <%= render 'users/list', user: @user, book: @book_new %>
    
    <div class="col-xs-9">
      <h2>Users</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size:"40x40" %>
              </td>
              <td><%= user.name %></td>
              <td><%= link_to "Show", user_path(user) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <%= notice %>
  <div class="row">
    <%= render 'users/list', user: @user, book: @book %>
    
    <div class="col-xs-9">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path, target: "_self" do %>
                  <%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size:"40x40" %>
                <% end %>
              </td>
              <td><%= link_to book_path(book.id) do %><%= book.title %><% end %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>